"""initial schema

Revision ID: 897441522362
Revises: 
Create Date: 2026-05-17 07:22:18.839767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '897441522362'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('capital', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('current_risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('active_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('HIGH', 'CRITICAL', name='alert_risk_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_alerts_state_id'), 'active_alerts', ['state_id'], unique=False)
    op.create_table('climate_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('air_quality_index', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('open_meteo', 'nasa_power', 'noaa_cdo', name='data_source'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_readings_state_id'), 'climate_readings', ['state_id'], unique=False)
    op.create_table('disease_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=True),
    sa.Column('disease_name', sa.String(length=200), nullable=False),
    sa.Column('alert_level', sa.Enum('watch', 'warning', 'emergency', name='disease_alert_level'), nullable=False),
    sa.Column('source', sa.Enum('ncdc', 'who_afro', name='disease_alert_source'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_lgas', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_alerts_state_id'), 'disease_alerts', ['state_id'], unique=False)
    op.create_table('government_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('ministry', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_contacts_state_id'), 'government_contacts', ['state_id'], unique=False)
    op.create_table('health_facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('lga', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('facility_type', sa.Enum('primary', 'secondary', 'tertiary', name='facility_type'), nullable=False),
    sa.Column('ownership', sa.Enum('public', 'private', 'ngo', 'faith_based', name='facility_ownership'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_facilities_lga'), 'health_facilities', ['lga'], unique=False)
    op.create_index(op.f('ix_health_facilities_state_id'), 'health_facilities', ['state_id'], unique=False)
    op.create_table('lga_vulnerability_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('lga_name', sa.String(length=100), nullable=False),
    sa.Column('vulnerability_score', sa.Float(), nullable=False),
    sa.Column('population_density_score', sa.Float(), nullable=False),
    sa.Column('health_access_score', sa.Float(), nullable=False),
    sa.Column('climate_exposure_score', sa.Float(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lga_vulnerability_scores_state_id'), 'lga_vulnerability_scores', ['state_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('climate_score', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('vulnerability_score', sa.Float(), nullable=False),
    sa.Column('advisory_en', sa.Text(), nullable=True),
    sa.Column('advisory_ha', sa.Text(), nullable=True),
    sa.Column('advisory_yo', sa.Text(), nullable=True),
    sa.Column('advisory_ig', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_state_id'), 'risk_assessments', ['state_id'], unique=False)
    op.create_table('risk_state_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('from_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('to_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_state_changes_state_id'), 'risk_state_changes', ['state_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state_id', sa.String(length=36), nullable=False),
    sa.Column('notify_moderate', sa.Boolean(), nullable=False),
    sa.Column('notify_high', sa.Boolean(), nullable=False),
    sa.Column('notify_critical', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_state_id'), 'user_subscriptions', ['state_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('facility_risk_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('flood_risk', sa.Float(), nullable=False),
    sa.Column('heat_stress_risk', sa.Float(), nullable=False),
    sa.Column('disease_burden_risk', sa.Float(), nullable=False),
    sa.Column('infrastructure_vulnerability', sa.Float(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['health_facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_risk_scores_facility_id'), 'facility_risk_scores', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_risk_scores_facility_id'), table_name='facility_risk_scores')
    op.drop_table('facility_risk_scores')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_state_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_risk_state_changes_state_id'), table_name='risk_state_changes')
    op.drop_table('risk_state_changes')
    op.drop_index(op.f('ix_risk_assessments_state_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_lga_vulnerability_scores_state_id'), table_name='lga_vulnerability_scores')
    op.drop_table('lga_vulnerability_scores')
    op.drop_index(op.f('ix_health_facilities_state_id'), table_name='health_facilities')
    op.drop_index(op.f('ix_health_facilities_lga'), table_name='health_facilities')
    op.drop_table('health_facilities')
    op.drop_index(op.f('ix_government_contacts_state_id'), table_name='government_contacts')
    op.drop_table('government_contacts')
    op.drop_index(op.f('ix_disease_alerts_state_id'), table_name='disease_alerts')
    op.drop_table('disease_alerts')
    op.drop_index(op.f('ix_climate_readings_state_id'), table_name='climate_readings')
    op.drop_table('climate_readings')
    op.drop_index(op.f('ix_active_alerts_state_id'), table_name='active_alerts')
    op.drop_table('active_alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('states')
    # ### end Alembic commands ###
